# -------------------- Configurable options  ---------------------
# gprof = -pg
CC           := gcc
CFLAGS       := -Wall -std=gnu11 -g -O3 -pedantic -MMD \
				-Werror=implicit-function-declaration
INCLUDE		 := -Iinclude/ -Ilib/CoCoNut-lib/include/
LFLAGS       := -L./lib/CoCoNut-lib/bin/
LDFLAGS      := -lmhash -lcoconut

AST_FILE	  			= test/pass/civic.ast
BIN_DIR 	  			= bin/
DOC_DIR 	  			= doc/
AST_GENERATED_SOURCES 	= src/generated/
AST_GENERATED_HEADERS	= include/generated/
AST_INTERNAL_HEADERS    = include/generated/internal/
AST_INTERNAL_SOURCES    = src/generated/internal/
SOURCES   	  			= src/core src/traversal src/passes
TARGET 	 	  			= civcc
DEBUG 					= @
